
import java.util.Scanner;

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char res = 0;
        if(s.length()>t.length()){
            res=s.charAt(s.length()-1);
        }else{
            res=t.charAt(t.length()-1);
        }
        return res;
    }
    public static void main(String[] args) {
        FindTheDifference fd = new FindTheDifference();
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the String1: ");
        String s = sc.nextLine();
        System.out.println("Enter the String2: ");
        String t = sc.nextLine();
        System.out.println(fd.findTheDifference(s, t));
    }
}
